#: import CheckBox kivy.uix.checkbox

<CustomLabel@Label>
    color: 0, 0, 0, 1

<CustomPopup>:
    size_hint: 0.5, .5
    auto_dismiss: False
    title: "The Popup"
    Button:
        text: "Close"
        on_press: root.dismiss()

SampleBoxLayout:

<SampleBoxLayout>:
    orientation: "vertical"
    padding: 10
    spacing: 10

    BoxLayout:
        orientation: "horizontal"
        size_hint_x: .5

        CustomLabel:
            text: "Are you over 18"
            size_hint_x: .8
        CheckBox:
            on_active: root.checkbox_18_clicked(self, self.active)
            size_hint_x: .55
        Image:
            source: ''


    BoxLayout:
        orientation: "horizontal"
        size_hint_x: .55

        CustomLabel:
            text: "Favorite Color"
            size_hint_x: .256
        CheckBox:
            group: "color"
            value: root.blue
            size_hint_x: .05
            active: True
        CustomLabel:
            text: "Blue"
            size_hint_x: .15
        CheckBox:
            group: "color"
            value: root.red
            size_hint_x: .05
            active: True
        CustomLabel:
            text: "Red"
            size_hint_x: .15
        CheckBox:
            group: "color"
            value: root.green
            size_hint_x: .05
        CustomLabel:
            text: "Green"
            size_hint_x: .15

    BoxLayout:
        orientation: "horizontal"
        height: 30

        BoxLayout:
            orientation: "horizontal"
            size_hint_x: .25

            CustomLabel:
                text: str(slider_id.value)

            Slider:
                id: slider_id
                min: -100
                max: 100
                value: 0
                step: 10

    BoxLayout:
        orientation: "horizontal"
        size_hint_x: .25

        CustomLabel:
            text: "On/Off"

        Switch:
            id: switch_id
            on_active: root.switch_on(self, self.active)

    BoxLayout:
        orientation: "horizontal"
        height: 30

        BoxLayout:
            orientation: "horizontal"
            size_hint_x: .25

            Button:
                text: "open popup"
                on_press: root.open_popup()

        BoxLayout:
            orientation: "horizontal"
            size_hint_x: .25

            Spinner:
                text: "First"
                values: ["First", "Second", "Third"]
                id: spinner_id
                on_text: root.spinner_clicked(spinner_id.text)

    BoxLayout:
        orientation: "horizontal"
        height: 30

        BoxLayout:
            orientation: "horizontal"
            size_hint_x: .25

            TabbedPanel:
                do_default_tab: False

                TabbedPanelItem:
                    text: "1st Tab"
                    Label:
                        text: "hello 1"
                TabbedPanelItem:
                    text: "2ndTab"
                    Label:
                        text: "hello 2"
                TabbedPanelItem:
                    text: "3rd Tab"
                    Label:
                        text: "hello 3"
