# Reference studentdb.py
#: import main studentdb
#: import ListAdapter kivy.adapters.listadapter.ListAdapter
#: import ListItemButton kivy.uix.listview.ListItemButton


StudentDB:                      #root-file

<StudentDB>:                    #BoxLayout
    orientation: "vertical"
    first_name_text_input: first_name
    last_name_text_input: last_name
    student_list: student_list_view

    padding: 10
    spacing: 30

    BoxLayout:
        size_hint_y: None
        height: "40dp"

        Label:
            text: "First name"
        TextInput:
            id: first_name

        Label:
            text: "Last name"
        TextInput:
            id: last_name

    BoxLayout:
        size_hint_y: None
        height: "40dp"
        Button:
            text: "Submit"
            size_hint_x: 15
            on_press: root.submit_student()
        Button:
            text: "Delete"
            size_hint_x: 15
            on_press: root.delete_student()
        Button:
            text: "Replace"
            size_hint_x: 15
            on_press: root.replace_student()

    ListView:
        id: student_list_view
        adapter:
            ListAdapter(data=["Test Name","Lukas Scheuerle"], cls=main.StudentListButton)