<CustomButton@Button>:
    font_size: 32

<CalcGridLayout>:
    id: calculator
    display: entry
    rows: 5
    padding: 10
    spacing: 10

    BoxLayout:
        TextInput:
            id: entry               #refer point
            font_size: 32
            multiline: False        #needs to be capital

    BoxLayout:
        spacing: 10
        CustomButton:
            text: "7"
            on_press: entry.text += self.text           #on_press: eventhandler
        CustomButton:
            text: "8"
            on_press: entry.text += self.text
        CustomButton:
            text: "9"
            on_press: entry.text += self.text
        CustomButton:
            text: "+"
            on_press: entry.text += self.text

    BoxLayout:
        spacing: 10
        CustomButton:
            text: "4"
            on_press: entry.text += self.text
        CustomButton:
            text: "5"
            on_press: entry.text += self.text
        CustomButton:
            text: "6"
            on_press: entry.text += self.text
        CustomButton:
            text: "-"
            on_press: entry.text += self.text

    BoxLayout:
        spacing: 10
        CustomButton:
            text: "1"
            on_press: entry.text += self.text
        CustomButton:
            text: "2"
            on_press: entry.text += self.text
        CustomButton:
            text: "3"
            on_press: entry.text += self.text
        CustomButton:
            text: "*"
            on_press: entry.text += self.text

    BoxLayout:
        spacing: 10
        CustomButton:
            text: "AC"
            on_press: entry.text = ""
        CustomButton:
            text: "0"
            on_press: entry.text += self.text
        CustomButton:
            text: "="
            on_press: calculator.calculate(entry.text)          #call calculate() from CalcGridLayout in main.py
        CustomButton:
            text: "/"
            on_press: entry.text += self.text